// <auto-generated />
namespace CafeApp.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addFoodType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFoodType));
        
        string IMigrationMetadata.Id
        {
            get { return "202004220707192_addFoodType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
